In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
import warnings

In [3]:
path = '/content/drive/MyDrive/Colab Notebooks/260327_202434919/titanic.csv'

df = pd.read_csv(path)

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [7]:
X = df.drop(['Survived', 'Pclass'], axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [8]:
#호출시
models = {
    "Logistic Regression": LogisticRegression(random_state=1000, max_iter=1000),
    "SVM": SVC(random_state=0),
    "Decision Tree": DecisionTreeClassifier(random_state=0),
    "Random Forest": RandomForestClassifier(random_state=0),
    "KNN": KNeighborsClassifier(n_neighbors=5)
}

In [9]:
models["Logistic Regression"].fit(X_train, y_train)
pred_lr = models["Logistic Regression"].predict(X_test)
print("\n--- Logistic Regression ---")
print(f"Accuracy: {accuracy_score(y_test, pred_lr):.4f}")
print(confusion_matrix(y_test, pred_lr))

--- Logistic Regression ---
Accuracy: 0.7758
[[115  24]
 [ 26  58]]

In [10]:
# --- SVM ---
models["SVM"].fit(X_train, y_train)
pred_svm = models["SVM"].predict(X_test)
print("\n--- SVM ---")
print(f"Accuracy: {accuracy_score(y_test, pred_svm):.4f}")
print(confusion_matrix(y_test, pred_svm))

--- SVM ---
Accuracy: 0.8117
[[120  19]
 [ 23  61]]

In [11]:
# --- Decision Tree ---
models["Decision Tree"].fit(X_train, y_train)
pred_dt = models["Decision Tree"].fit(X_train, y_train).predict(X_test)
print("\n--- Decision Tree ---")
print(f"Accuracy: {accuracy_score(y_test, pred_dt):.4f}")
print(confusion_matrix(y_test, pred_dt))

--- Decision Tree ---
Accuracy: 0.7668
[[116  23]
 [ 29  55]]

In [12]:
# --- Random Forest ---
models["Random Forest"].fit(X_train, y_train)
pred_rf = models["Random Forest"].predict(X_test)
print("\n--- Random Forest ---")
print(f"Accuracy: {accuracy_score(y_test, pred_rf):.4f}")
print(confusion_matrix(y_test, pred_rf))

--- Random Forest ---
Accuracy: 0.8161
[[119  20]
 [ 21  63]]

In [13]:
# --- KNN ---
models["KNN"].fit(X_train, y_train)
pred_knn = models["KNN"].predict(X_test)
print("\n--- KNN ---")
print(f"Accuracy: {accuracy_score(y_test, pred_knn):.4f}")
print(confusion_matrix(y_test, pred_knn))

--- KNN ---
Accuracy: 0.8206
[[119  20]
 [ 20  64]]